// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exqtewjwhoaqnthbdfuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4cXRld2p3aG9hcW50aGJkZnVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzODMxODIsImV4cCI6MjA3Njk1OTE4Mn0.5lsWp-Z4cwGwmBdCvWhDiLgFBH5Gvq1wnEog307wilc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});